import type { Metadata } from 'next';
import './globals.css';
import { cn } from '@/lib/utils';
import { roboto, inter } from './fonts';
import { Provider } from 'react-redux';
import StoreProvider from './store-provider';
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from '../components/ui/toast-container';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <StoreProvider>
        <body className={cn(roboto.className, inter.variable)}>
          {children}
          <ToastContainer />
        </body>
      </StoreProvider>
    </html>
  );
}
